language: rust
rust:
  - stable
cache: cargo
git:
  depth: 1
jobs:
  include:
    - stage: check
      name: Tests
      script: cargo test
    - stage: check
      name : Rustfmt
      install: rustup component add rustfmt
      script: cargo fmt -- --check
    - stage: check
      name: Clippy
      install: rustup component add clippy
      script: cargo clippy
    - stage: build
      name: Package
      script: cargo package
    - stage: build
      name: Build w/o features
      script: cargo build
    - stage: build
      name: Build with queue-counter feature
      script: cargo build --features queue-counter
    ## Require 'svc-authn' w/ diesel feature
    # - stage: build
    #   name: Build w/ diesel
    #   script: cargo build --features "diesel"
stages:
  - name: check
  - name: build
notifications:
  email: false
