[package]
name = "svc-agent"
version = "0.19.3"
authors = ["Andrei Nesterov <ae.nesterov@gmail.com>"]
description = "An agent library."
readme = "README.md"
keywords = ["agent", "mqtt", "pubsub", "messaging-patterns", "event-driven"]
categories = ["network-programming", "web-programming"]
repository = "https://github.com/netology-group/svc-agent-rs"
license = "MIT"
edition = "2018"

[badges]
travis-ci = { repository = "netology-group/svc-agent-rs" }

[lib]
doctest = false

[features]
queue-counter = []

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.13"
diesel = { version = "1", features = ["postgres"], optional = true }
sqlx = { version = "0.5", features = ["runtime-tokio-native-tls", "postgres"], optional = true }
rumqttc = "0.7"
http = "0.2"
svc-authn = "0.7"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
log = "0.4"
tokio = { version = "1", features = ["rt-multi-thread", "time"] }
async-channel = "1"
