[package]
name = "svc-agent"
version = "0.13.1"
authors = ["Andrei Nesterov <ae.nesterov@gmail.com>"]
description = "An agent library."
readme = "README.md"
keywords = ["agent", "mqtt", "pubsub", "messaging-patterns", "event-driven"]
categories = ["network-programming", "web-programming"]
repository = "https://github.com/netology-group/svc-agent-rs"
license = "MIT"
edition = "2018"

[badges]
travis-ci = { repository = "netology-group/svc-agent-rs" }

[lib]
doctest = false

[features]
queue-counter = []

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
base64 = "0.10"
diesel = { version = "1.4", features = ["postgres"], optional = true }
rumqtt = "0.31"
http = "0.1"
svc-authn = "0.5"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
futures = "0.3"
futures-channel = "0.3"
crossbeam-channel = "0.3"
log = "0.4"
